### ISSUE TITLE
Improve docs & error messages for use of VersionedForeignKey vs ForeignKey

### ISSUE THREAD

**Issue by ezheidtmann** [swisscom/cleanerversion#54] opened 2015-02-03 20:26 UTC
I am just learning CleanerVersion and I think I just learned that one should use VersionedForeignKey to point to a Versionable model, but use ForeignKey to point to an unversioned model.

I didn't get this from the docs. Maybe there is a way to mention it in there.

I also didn't get this from the error message I get when trying to display that field in the admin:

```
/lib/python2.7/site-packages/versions/models.py", line 619, in __get__
raise TypeError("It seems like " + str(type(self)) + " is not a Versionable")
TypeError: It seems like <class 'versions.models.VersionedReverseSingleRelatedObjectDescriptor'> is not a Versionable
```

I think at least, this message should indicate which field and model are set up incorrectly.

(Or maybe I'm missing something and I'm all wrong ...)

Sorry, I don't have a patch for either of these now. Maybe soon. :-)

**Comment by maennel** [comment] 2015-02-03 20:40
Hi @ezheidtmann, 
well, I think this is our fault... Actually, the doc-part you're referring to has been [merged into master yesterday](https://github.com/swisscom/cleanerversion/blob/master/docs/doc/historization_with_cleanerversion.rst#integrating-cleanerversion-versioned-models-with-non-versioned-models).
Since then, no one has triggered the update on [readthedocs](http://cleanerversion.readthedocs.org/). I've done that now. Sorry for the inconvenience.
Regarding the error message, feel free to submit a more adequate suggestion.
Thanks, 
-Manuel

**Comment by maennel** [comment] 2015-02-06 12:32
In the meanwhile, I guess it's ok to close this issue.
Let me know, if there's anything else...
-Manuel

**Closed by maennel** 2015-02-06 12:32 UTC

**Comment by raphaelm** [comment] 2015-02-11 23:40
I'd like to add two minor comments.

@ezheidtmann:
> I also didn't get this from the error message I get when trying to display that field in the admin:

I would be happy to be told that I'm wrong on this, but I think the docs should stress that in general it is not a good idea to use Django's admin panel together with cleanerversion, as it will lead to unexpected behaviour (e.g. you loose history, as the admin does not call ``.clone()`` and everyone who uses the admin has to know about cleanerversion's internals).

@maennel:
> Since then, no one has triggered the update on readthedocs. I've done that now. Sorry for the inconvenience.

You can setup a web hook in the repository's settings to automate this :)

**Comment by ezheidtmann** [comment] 2015-02-24 01:02
As for the error message, I'd like to see something like this:

```
TypeError: It seems like <class 'yourapp.models.MyModelClass'> is not a Versionable
```

I think you can get there by revising the line shown in the traceback to this:

```python
            raise TypeError("It seems like " + str(type(current_elt)) + " is not a Versionable")
```

@raphaelm Do you know if anyone has attempted to patch the admin's behavior to work with cleanerversion? I tried briefly by calling `.clone()` in `save_model()` but the results were confusing.

**Comment by raphaelm** [comment] 2015-02-24 08:35
No, I do not know of any attempt to support cleanerversion in the admin and I guess it's a bit complicated to do so, as you would not want the admin to list all versions of an object as distinct objects with the same identity, but you would like to group them in a way that makes sense, which would require big changes to the admin code.

**Comment by maennel** [comment] 2015-02-24 10:33
@ezheidtmann Indeed, as @raphaelm pointed out, integration to the admin view is currently not on our roadmap at all. Which means, that we currently cannot invest much time into developing this feature (except our free time). 
However, I don't exclude that it's coming sooner or later... Therefore, I'd suggest that you write a separate issue dedicated to that topic, listing the requirements that you would like to have implemented by such an integration.
Perhaps it would also make sense to add a note to the "Known issues" part in the docs, as @raphaelm mentioned in an earlier comment on this issue.

Thanks!
-Manuel

PS: @raphaelm thanks for the web hook tip! I'll try it out. :)
